[web]
10.0.0.5

[monitoring]
10.0.0.136

[exporters]
10.0.0.5
10.0.0.136
10.0.0.135 

[all:vars]
ansible_connection=ssh
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ssm-user/.ssh/ansible_key
ansible_ssh_common_args='-o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new'
